## Importação de arquivos e bibliotecas

In [3]:
# Importação bibliotecas
import pandas as pd

In [ ]:
# Importação das bases

df_produtos = pd.read_csv(r'../data/raw/produtos_raw.csv')

df_vendas = pd.read_csv(r'../data/raw/vendas_2023_2024.csv')

df_clientes = pd.read_json(r'../data/raw/clientes_crm.json')

df_custos_importacao =  pd.read_json(r'../data/raw/custos_importacao.json')

## Tratamento produtos

In [46]:
df_produtos.head(70)

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,ELETRONICOS
1,Transponder Furuno Marlin,R$ 13998.15,2,ELETRONICOS
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,E L E T R Ô N I C O S
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,Eletronicoz
...,...,...,...,...
65,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Prop
66,Motor Elétrico Torqeedo Ion Orca Vox 186HP,R$ 139957.67,63,pRoPuLsÃo
67,Motor Elétrico Yamaha Swift Drift Current 265HP,R$ 111505.55,64,pRoPuLsÃo
68,Motor de Popa Torqeedo Nautic Swift 223HP,R$ 25557.7,65,Propulção
69,Motor de Popa Tohatsu Poseidon Helix Prime 135HP,R$ 12571.63,66,Propulçao

### name

In [47]:
df_produtos["name"].value_counts().index.to_list()

['Motor Diesel Yanmar Velocity 37HP',
 'Boia de Arqueamento Delta Nexus',
 'GPS Lowrance Evo Storm Drift',
 'Cabo de Nylon Delta Velocity Core Mako',
 'Transponder AIS Maré Magnum',
 'Transponder Furuno Marlin',
 'Radar AIS Zen',
 'GPS AIS Zen',
 'Transponder AIS Titan Pulse',
 'Piloto Automático Simrad Titan Flux Magnum',
 'GPS Furuno Swift Leviathan Poseidon',
 'GPS AIS Drift Flux Vox',
 'Radar Simrad Boost',
 'Rádio Furuno Zen Swift',
 'Radar Garmin Tidal Thrust',
 'Sonda Garmin Axis',
 'Rádio AIS Oceanic Pulse',
 'Rádio Simrad Axis',
 'Radar Furuno Pulse Leviathan',
 'Rádio AIS Hydro Tidal Zen',
 'Piloto Automático Furuno Storm',
 'Transponder AIS Vector',
 'Transponder Furuno Force Ion',
 'GPS AIS Nautic Thrust',
 'Radar AIS Marlin',
 'Sonda Lowrance Tidal Storm Vox',
 'GPS Garmin Vortex Maré Drift',
 'Piloto Automático AIS Core',
 'Rádio Lowrance Nitro Thrust Barracuda',
 'Piloto Automático Furuno Torque Peak',
 'Transponder AIS Boost',
 'Transponder Furuno Pulse Axis',
 'Transponder Garmin Drift Vortex Marlin',
 'Sonda AIS Impulse Oceanic Zenith',
 'Transponder AIS Helix Torque',
 'Radar Furuno Swift',
 'Rádio Simrad Orca',
 'GPS AIS Orca Marlin Velocity',
 'GPS Furuno Vector',
 'Sonda Furuno Maré Tidal',
 'GPS Simrad Flow Pulse',
 'Transponder Lowrance Axis',
 'Sonda AIS Barracuda',
 'GPS Simrad Zen Hydra Peak',
 'GPS Furuno Current',
 'Sonda AIS Magnum Boost',
 'Rádio Simrad Tidal Aqua',
 'GPS Furuno Magnum Drift',
 'Sonda Furuno Swift',
 'Piloto Automático Simrad Poseidon Magnum',
 'Motor Diesel Tohatsu Evo Zenith 16HP',
 'Motor Diesel Honda Zen Tidal Mako 26HP',
 'Radar Lowrance Aqua Pulse',
 'Piloto Automático Furuno Core Boost Flux',
 'Motor de Popa Yamaha Evo Dash 155HP',
 'Motor Diesel Volvo Flow Oceanic 259HP',
 'Motor de Popa Honda Vector Kinetic 174HP',
 'Motor Elétrico Torqeedo Velocity Swift 74HP',
 'Motor de Popa Tohatsu Ion Core Nautic 53HP',
 'Motor Diesel Yanmar Hydro Magnum Boost 267HP',
 'Motor de Popa Honda Velocity Drift 258HP',
 'Motor Diesel Honda Prime 84HP',
 'Motor Elétrico Torqeedo Ion Orca Vox 186HP',
 'Motor Elétrico Yamaha Swift Drift Current 265HP',
 'Motor de Popa Torqeedo Nautic Swift 223HP',
 'Motor de Popa Tohatsu Poseidon Helix Prime 135HP',
 'Motor de Popa Yamaha Mako 108HP',
 'Motor de Popa Honda Ion Vox Prime 163HP',
 'Motor de Popa Torqeedo Ultra Impulse 292HP',
 'Motor Diesel Parsun Boost Helix Velocity 146HP',
 'Motor Elétrico Torqeedo Pulse 300HP',
 'Motor de Popa Volvo Hydro Dash 256HP',
 'Motor de Popa Torqeedo Core Hydra Flux 162HP',
 'Motor de Popa Honda Torque 228HP',
 'Motor Diesel Volvo Flow Leviathan Maré 187HP',
 'Motor Diesel Honda Aero 205HP',
 'Motor Diesel Tohatsu Vector 197HP',
 'Motor Elétrico Honda Mako Axis 131HP',
 'Motor Diesel Tohatsu Zenith 60HP',
 'Motor de Popa Volvo Maré 69HP',
 'Motor Elétrico Torqeedo Barracuda Magnum Helix 101HP',
 'Motor Elétrico Volvo Nautic Vox 118HP',
 'Motor Diesel Yanmar Dash Nitro 184HP',
 'Motor de Popa Torqeedo Zenith Peak Thrust 212HP',
 'Motor Elétrico Torqeedo Zen Titan Hydra 129HP',
 'Rádio AIS Force',
 'Motor Diesel Volvo Helix Evo Force 144HP',
 'Motor de Popa Parsun Impulse 162HP',
 'Motor Elétrico Volvo Boost 225HP',
 'Motor Diesel Tohatsu Kinetic Poseidon 113HP',
 'Motor Elétrico Tohatsu Zenith Oceanic 113HP',
 'Motor Elétrico Yamaha Nautic Kraken 133HP',
 'Motor Elétrico Yamaha Orca Storm Zenith 11HP',
 'Motor de Popa Yamaha Thrust Marlin Nexus 182HP',
 'Motor Diesel Honda Leviathan 133HP',
 'Motor de Popa Tohatsu Boost Swift 126HP',
 'Motor de Popa Tohatsu Evo 168HP',
 'Motor Diesel Parsun Velocity Abyss Orca 235HP',
 'Motor Elétrico Honda Flux Ultra 273HP',
 'Motor Elétrico Honda Vector Abyss 220HP',
 'Motor Elétrico Yamaha Flow 204HP',
 'Motor de Popa Volvo Magnum 276HP',
 'Âncora Delta Swift',
 'Cabo de Nylon Delta Zen Vortex Storm',
 'Cabo de Nylon Danforth Prime',
 'Âncora Danforth Nitro Titan Vox',
 'Boia de Arqueamento Bruce Tidal Marlin',
 'Boia de Arqueamento Bruce Titan',
 'Cabo de Nylon Danforth Evo Aqua Mako',
 'Corrente Bruce Current',
 'Boia de Arqueamento Danforth Aero Dash',
 'Corrente Danforth Tidal',
 'Âncora Delta Mako Ultra',
 'Boia de Arqueamento Danforth Tidal Zen Swift',
 'Cabo de Nylon Delta Force Magnum Leviathan',
 'Cabo de Nylon Delta Velocity Oceanic Abyss',
 'Cabo de Nylon Delta Vortex',
 'Cabo de Nylon Bruce Nexus',
 'Boia de Arqueamento Delta Force Vox',
 'Corrente Danforth Zen Abyss Axis',
 'Boia de Arqueamento Danforth Flux Tidal',
 'Âncora Bruce Aqua',
 'Corrente Danforth Zenith Oceanic Torque',
 'Cabo de Nylon Danforth Orca Aero',
 'Corrente Delta Axis',
 'Âncora Danforth Oceanic Helix Flux',
 'Cabo de Nylon Danforth Kinetic',
 'Corrente Danforth Hydro',
 'Boia de Arqueamento Bruce Marlin Hydra',
 'Corrente Delta Boost',
 'Boia de Arqueamento Delta Zen Boost Vortex',
 'Boia de Arqueamento Danforth Core Vortex',
 'Corrente Bruce Nautic Evo',
 'Âncora Bruce Core Pulse',
 'Âncora Delta Storm Vox',
 'Cabo de Nylon Danforth Titan Poseidon',
 'Cabo de Nylon Bruce Flux Hydro',
 'Âncora Danforth Impulse',
 'Boia de Arqueamento Delta Peak Boost Thrust',
 'Boia de Arqueamento Danforth Torque',
 'Boia de Arqueamento Bruce Dash Titan Pulse',
 'Boia de Arqueamento Bruce Nexus Abyss',
 'Âncora Danforth Vector Evo',
 'Âncora Delta Hydra Kraken Velocity',
 'Boia de Arqueamento Bruce Barracuda',
 'Corrente Delta Vox Ion',
 'Corrente Danforth Force Leviathan Impulse',
 'Âncora Delta Force Barracuda Mako',
 'Cabo de Nylon Bruce Core',
 'Cabo de Nylon Danforth Magnum Vox']

### price

In [48]:
# Limpeza de preço e transformação em float

df_produtos["price"] = df_produtos["price"].str.replace("R$ ", "")
df_produtos["price"] = pd.to_numeric(df_produtos["price"])

In [49]:
# Limpeza de produtos
df_produtos["name"].value_counts().index.to_list()

['Motor Diesel Yanmar Velocity 37HP',
 'Boia de Arqueamento Delta Nexus',
 'GPS Lowrance Evo Storm Drift',
 'Cabo de Nylon Delta Velocity Core Mako',
 'Transponder AIS Maré Magnum',
 'Transponder Furuno Marlin',
 'Radar AIS Zen',
 'GPS AIS Zen',
 'Transponder AIS Titan Pulse',
 'Piloto Automático Simrad Titan Flux Magnum',
 'GPS Furuno Swift Leviathan Poseidon',
 'GPS AIS Drift Flux Vox',
 'Radar Simrad Boost',
 'Rádio Furuno Zen Swift',
 'Radar Garmin Tidal Thrust',
 'Sonda Garmin Axis',
 'Rádio AIS Oceanic Pulse',
 'Rádio Simrad Axis',
 'Radar Furuno Pulse Leviathan',
 'Rádio AIS Hydro Tidal Zen',
 'Piloto Automático Furuno Storm',
 'Transponder AIS Vector',
 'Transponder Furuno Force Ion',
 'GPS AIS Nautic Thrust',
 'Radar AIS Marlin',
 'Sonda Lowrance Tidal Storm Vox',
 'GPS Garmin Vortex Maré Drift',
 'Piloto Automático AIS Core',
 'Rádio Lowrance Nitro Thrust Barracuda',
 'Piloto Automático Furuno Torque Peak',
 'Transponder AIS Boost',
 'Transponder Furuno Pulse Axis',
 'Transponder Garmin Drift Vortex Marlin',
 'Sonda AIS Impulse Oceanic Zenith',
 'Transponder AIS Helix Torque',
 'Radar Furuno Swift',
 'Rádio Simrad Orca',
 'GPS AIS Orca Marlin Velocity',
 'GPS Furuno Vector',
 'Sonda Furuno Maré Tidal',
 'GPS Simrad Flow Pulse',
 'Transponder Lowrance Axis',
 'Sonda AIS Barracuda',
 'GPS Simrad Zen Hydra Peak',
 'GPS Furuno Current',
 'Sonda AIS Magnum Boost',
 'Rádio Simrad Tidal Aqua',
 'GPS Furuno Magnum Drift',
 'Sonda Furuno Swift',
 'Piloto Automático Simrad Poseidon Magnum',
 'Motor Diesel Tohatsu Evo Zenith 16HP',
 'Motor Diesel Honda Zen Tidal Mako 26HP',
 'Radar Lowrance Aqua Pulse',
 'Piloto Automático Furuno Core Boost Flux',
 'Motor de Popa Yamaha Evo Dash 155HP',
 'Motor Diesel Volvo Flow Oceanic 259HP',
 'Motor de Popa Honda Vector Kinetic 174HP',
 'Motor Elétrico Torqeedo Velocity Swift 74HP',
 'Motor de Popa Tohatsu Ion Core Nautic 53HP',
 'Motor Diesel Yanmar Hydro Magnum Boost 267HP',
 'Motor de Popa Honda Velocity Drift 258HP',
 'Motor Diesel Honda Prime 84HP',
 'Motor Elétrico Torqeedo Ion Orca Vox 186HP',
 'Motor Elétrico Yamaha Swift Drift Current 265HP',
 'Motor de Popa Torqeedo Nautic Swift 223HP',
 'Motor de Popa Tohatsu Poseidon Helix Prime 135HP',
 'Motor de Popa Yamaha Mako 108HP',
 'Motor de Popa Honda Ion Vox Prime 163HP',
 'Motor de Popa Torqeedo Ultra Impulse 292HP',
 'Motor Diesel Parsun Boost Helix Velocity 146HP',
 'Motor Elétrico Torqeedo Pulse 300HP',
 'Motor de Popa Volvo Hydro Dash 256HP',
 'Motor de Popa Torqeedo Core Hydra Flux 162HP',
 'Motor de Popa Honda Torque 228HP',
 'Motor Diesel Volvo Flow Leviathan Maré 187HP',
 'Motor Diesel Honda Aero 205HP',
 'Motor Diesel Tohatsu Vector 197HP',
 'Motor Elétrico Honda Mako Axis 131HP',
 'Motor Diesel Tohatsu Zenith 60HP',
 'Motor de Popa Volvo Maré 69HP',
 'Motor Elétrico Torqeedo Barracuda Magnum Helix 101HP',
 'Motor Elétrico Volvo Nautic Vox 118HP',
 'Motor Diesel Yanmar Dash Nitro 184HP',
 'Motor de Popa Torqeedo Zenith Peak Thrust 212HP',
 'Motor Elétrico Torqeedo Zen Titan Hydra 129HP',
 'Rádio AIS Force',
 'Motor Diesel Volvo Helix Evo Force 144HP',
 'Motor de Popa Parsun Impulse 162HP',
 'Motor Elétrico Volvo Boost 225HP',
 'Motor Diesel Tohatsu Kinetic Poseidon 113HP',
 'Motor Elétrico Tohatsu Zenith Oceanic 113HP',
 'Motor Elétrico Yamaha Nautic Kraken 133HP',
 'Motor Elétrico Yamaha Orca Storm Zenith 11HP',
 'Motor de Popa Yamaha Thrust Marlin Nexus 182HP',
 'Motor Diesel Honda Leviathan 133HP',
 'Motor de Popa Tohatsu Boost Swift 126HP',
 'Motor de Popa Tohatsu Evo 168HP',
 'Motor Diesel Parsun Velocity Abyss Orca 235HP',
 'Motor Elétrico Honda Flux Ultra 273HP',
 'Motor Elétrico Honda Vector Abyss 220HP',
 'Motor Elétrico Yamaha Flow 204HP',
 'Motor de Popa Volvo Magnum 276HP',
 'Âncora Delta Swift',
 'Cabo de Nylon Delta Zen Vortex Storm',
 'Cabo de Nylon Danforth Prime',
 'Âncora Danforth Nitro Titan Vox',
 'Boia de Arqueamento Bruce Tidal Marlin',
 'Boia de Arqueamento Bruce Titan',
 'Cabo de Nylon Danforth Evo Aqua Mako',
 'Corrente Bruce Current',
 'Boia de Arqueamento Danforth Aero Dash',
 'Corrente Danforth Tidal',
 'Âncora Delta Mako Ultra',
 'Boia de Arqueamento Danforth Tidal Zen Swift',
 'Cabo de Nylon Delta Force Magnum Leviathan',
 'Cabo de Nylon Delta Velocity Oceanic Abyss',
 'Cabo de Nylon Delta Vortex',
 'Cabo de Nylon Bruce Nexus',
 'Boia de Arqueamento Delta Force Vox',
 'Corrente Danforth Zen Abyss Axis',
 'Boia de Arqueamento Danforth Flux Tidal',
 'Âncora Bruce Aqua',
 'Corrente Danforth Zenith Oceanic Torque',
 'Cabo de Nylon Danforth Orca Aero',
 'Corrente Delta Axis',
 'Âncora Danforth Oceanic Helix Flux',
 'Cabo de Nylon Danforth Kinetic',
 'Corrente Danforth Hydro',
 'Boia de Arqueamento Bruce Marlin Hydra',
 'Corrente Delta Boost',
 'Boia de Arqueamento Delta Zen Boost Vortex',
 'Boia de Arqueamento Danforth Core Vortex',
 'Corrente Bruce Nautic Evo',
 'Âncora Bruce Core Pulse',
 'Âncora Delta Storm Vox',
 'Cabo de Nylon Danforth Titan Poseidon',
 'Cabo de Nylon Bruce Flux Hydro',
 'Âncora Danforth Impulse',
 'Boia de Arqueamento Delta Peak Boost Thrust',
 'Boia de Arqueamento Danforth Torque',
 'Boia de Arqueamento Bruce Dash Titan Pulse',
 'Boia de Arqueamento Bruce Nexus Abyss',
 'Âncora Danforth Vector Evo',
 'Âncora Delta Hydra Kraken Velocity',
 'Boia de Arqueamento Bruce Barracuda',
 'Corrente Delta Vox Ion',
 'Corrente Danforth Force Leviathan Impulse',
 'Âncora Delta Force Barracuda Mako',
 'Cabo de Nylon Bruce Core',
 'Cabo de Nylon Danforth Magnum Vox']

### code

In [22]:
# Não precisa de limpeza

### actual_category

In [50]:
df_produtos["actual_category"].value_counts()

actual_category
AncorageM                9
Propução                 8
Ancoraguem               8
eletrônicos              7
Eletronicoz              7
E L E T R Ô N I C O S    6
ELETRONICOS              6
P R O P U L S Ã O        6
propulsão                6
PROPULSAO                6
Eletrunicos              5
Ancorajm                 5
eLeTrÔnIcOs              5
Propulssão               5
Propulção                5
Prop                     5
Encoragem                5
aNcOrAgEm                5
A N C O R A G E M        5
Eletrônicos              4
propulsao                4
EletrônicoS              3
Propulçao                3
Ancorajem                3
eletronicos              3
Ancoragem                3
Ancorajen                2
Eletronicos              2
Propulsam                2
Eletroniscos             2
pRoPuLsÃo                2
ancoragem                2
AnCoRaGeM                2
ELEtRÔNICOS              1
PrOpUlSãO                1
Encoragi                 1
ANCORAGEM                1
AncorajeM                1
Ancoragen                1
Name: count, dtype: int64

In [51]:
# Minimizando as letras e tirando espaços entre palavras

#for data in df["actual_category"]:
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace(" ", "").str.lower()
df_produtos["actual_category"]

#Limpeza eletrônicos
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("eletronicos", "eletrônicos")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("eletronicoz", "eletrônicos")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("eletrunicos", "eletrônicos")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("eletroniscos", "eletrônicos")

#Limpeza propulsão  
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("propulsao", "propulsão")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("propução", "propulsão")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("prop", "propulsão")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("propulsãoulsão", "propulsão")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("propulsãoulssão", "propulsão")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("propulsãoulçao", "propulsão")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("propulsãoulsam", "propulsão")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("propulsãoulção", "propulsão")

#Limpeza eletrônicos
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("ancoraguem", "ancoragem")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("encoragem", "ancoragem")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("ancorajm", "ancoragem")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("ancorajem", "ancoragem")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("ancorajen", "ancoragem")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("encoragi", "ancoragem")
df_produtos["actual_category"] = df_produtos["actual_category"].str.replace("ancoragen", "ancoragem")

### Feature engeneering de produtos

In [52]:
df_produtos.rename(columns={'name': 'produto','price': 'preco','code': 'id_produto', 'actual_category': 'categoria_produto'}, inplace=True)
df_produtos.head()

                          produto     preco  id_produto categoria_produto
0     Transponder AIS Maré Magnum  33122.52           1       eletrônicos
1       Transponder Furuno Marlin  13998.15           2       eletrônicos
2    Radar Furuno Pulse Leviathan   9024.19           3       eletrônicos
3       Rádio AIS Hydro Tidal Zen   3381.88           4       eletrônicos
4  Piloto Automático Furuno Storm  23669.01           5       eletrônicos

In [53]:
df_produtos["subcategoria_produto"] = df_produtos['produto'].str.split().str[0]
df_produtos.head()

,produto,preco,id_produto,categoria_produto,subcategoria_produto
0,Transponder AIS Maré Magnum,33122.52,1,eletrônicos,Transponder
1,Transponder Furuno Marlin,13998.15,2,eletrônicos,Transponder
2,Radar Furuno Pulse Leviathan,9024.19,3,eletrônicos,Radar
3,Rádio AIS Hydro Tidal Zen,3381.88,4,eletrônicos,Rádio
4,Piloto Automático Furuno Storm,23669.01,5,eletrônicos,Piloto

## Tratamento vendas

In [54]:
df_vendas.head()

   id  id_client  id_product  qtd     total   sale_date
0   0         42         105   11    3405.0  2023-09-10
1   1          3         136    9   16873.9  15-09-2024
2   2         25         139    7    9475.3  2024-08-13
3   4         20          23    5   55893.0  2023-02-03
4   5          8          57    4  451403.9  2024-02-12

In [55]:
df_vendas[["sale_date"]].value_counts()

sale_date
11-03-2024    16
04-02-2024    15
06-09-2023    15
11-04-2024    14
04-09-2024    14
              ..
20-09-2023     1
25-03-2024     1
2023-08-17     1
2024-02-16     1
2024-08-05     1
Name: count, Length: 1446, dtype: int64

### sales_date

In [56]:
df_vendas["sale_date"] = pd.to_datetime(df_vendas["sale_date"], format='mixed')
df_vendas.head()

   id  id_client  id_product  qtd     total  sale_date
0   0         42         105   11    3405.0 2023-09-10
1   1          3         136    9   16873.9 2024-09-15
2   2         25         139    7    9475.3 2024-08-13
3   4         20          23    5   55893.0 2023-02-03
4   5          8          57    4  451403.9 2024-02-12

### Feature engeneering de vendas

In [57]:
df_vendas.rename(columns={'id': 'id_vendas', 'sale_date': 'data_venda'}, inplace=True)
df_vendas.head()

   id_vendas  id_client  id_product  qtd     total data_venda
0          0         42         105   11    3405.0 2023-09-10
1          1          3         136    9   16873.9 2024-09-15
2          2         25         139    7    9475.3 2024-08-13
3          4         20          23    5   55893.0 2023-02-03
4          5          8          57    4  451403.9 2024-02-12

In [58]:
df_vendas.dtypes

id_vendas              int64
id_client              int64
id_product             int64
qtd                    int64
total                float64
data_venda    datetime64[ns]
dtype: object

## Tratamento Clientes

In [59]:
#df_clientes["location"].value_counts()

ufs = [
    'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 
    'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 
    'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
]
#df_clientes["location"] = df_clientes["location"].strip()
#df_clientes["location"].head()

In [60]:
local = df_clientes["location"]

In [61]:
def extrair_estado_cidade(local):
    if not isinstance(local, str):
        return None, None
    
    local = local.strip()
    
    # 🔹 1. Verifica início
    possivel_uf = local[:2]
    
    if possivel_uf in ufs:
        cidade = local[2:].strip(" -_,/")
        return possivel_uf, cidade
    
    # 🔹 2. Verifica final
    possivel_uf = local[-2:]
    
    if possivel_uf in ufs:
        cidade = local[:-2].strip(" -_,/")
        return possivel_uf, cidade
    
    # 🔹 3. Caso não encontre
    return None, local

In [62]:
df_clientes[['estado', 'cidade']] = df_clientes["location"].apply(
    lambda x: pd.Series(extrair_estado_cidade(x))
)

df_clientes.head()

,full_name,location,code,email,estado,cidade
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com,BA,Aratu (Candeias)
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com,PE,Recife
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com,RS,Rio Grande
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com,AC,Rio Branco
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com,PA,Santarém Novo

In [64]:
# Tratamento e-mail
df_clientes["email"] = df_clientes["email"].str.replace("#", "@")
df_clientes.head(100)

,full_name,location,code,email,estado,cidade
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com,BA,Aratu (Candeias)
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com,PE,Recife
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro@gmail.com,RS,Rio Grande
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira@gmail.com,AC,Rio Branco
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas@icloud.com,PA,Santarém Novo
5,Antônia Coelho Pinheiro Peixoto Cavalcanti,"Fortaleza do Tabocão , TO",6,coelho.pinheiro.peixoto.antônia.cavalcanti@aol...,TO,Fortaleza do Tabocão
6,Bianca Barros Rocha Torres Siqueira,PB/Cabedelo,7,torres.barros.rocha.bianca.siqueira@aol.com,PB,Cabedelo
7,Luiz Alves Pimentel,SE - Aracaju,8,pimentel.alves.luiz@outlook.com,SE,Aracaju
8,Lucas Guedes Cunha Lopes,PB - João Pessoa,9,lucas.lopes.guedes.cunha@tutanota.com,PB,João Pessoa
9,Débora Paiva,Santarém / PA,10,paiva.débora@gmx.com,PA,Santarém
10,Victor Torres Monteiro,BA - Porto Seguro,11,torres.monteiro.victor@gmail.com,BA,Porto Seguro
11,Rafael Pereira Barros,"TO , Fortaleza do Tabocão",12,rafael.pereira.barros@zoho.com,TO,Fortaleza do Tabocão
12,Carlos Guimarães Martins,PA / Santarém,13,martins.guimarães.carlos@hotmail.com,PA,Santarém
13,Gabriela Silva Vieira Amaral,"AM , Itacoatiara",14,vieira.silva.amaral.gabriela@icloud.com,AM,Itacoatiara
14,Carla Lopes Alves Pacheco Rocha,"Fortaleza do Tabocão,TO",15,lopes.alves.pacheco.rocha.carla@yahoo.com,TO,Fortaleza do Tabocão
15,Renata Pacheco Cardoso,"Fortaleza,CE",16,renata.pacheco.cardoso@zoho.com,CE,Fortaleza
16,Luís Paiva Costa Cardoso Coelho,MS - Corumbá,17,costa.paiva.luís.coelho.cardoso@aol.com,MS,Corumbá
17,Adriana Guedes Borges Alves Rocha,Santarém - PA,18,rocha.adriana.guedes.borges.alves@protonmail.com,PA,Santarém
18,Renata Lima Gomes Coelho Mendonça,Maceió / AL,19,renata.lima.mendonça.coelho.gomes@icloud.com,AL,Maceió
19,Bruno Silva,"PA , Santarém Novo",20,silva.bruno@zoho.com,PA,Santarém Novo
20,Sandra Rocha Oliveira Soares Peixoto,"AC,Rio Branco",21,peixoto.soares.rocha.oliveira.sandra@yahoo.com,AC,Rio Branco
21,Daniela Borges Vieira Farias Mendonça,SE / Aracaju,22,borges.vieira.daniela.mendonça.farias@protonma...,SE,Aracaju
22,Bruna Mendonça Rodrigues,Santos - SP,23,rodrigues.mendonça.bruna@aol.com,SP,Santos
23,Carla Peixoto Azevedo Silva Araújo,Laguna / SC,24,peixoto.carla.araújo.silva.azevedo@outlook.com,SC,Laguna
24,Femininos Antunes Lopes Ribeiro Amaral,ES / São Mateus,25,femininos.antunes.amaral.lopes.ribeiro@icloud.com,ES,São Mateus
25,Luiz Borges Gomes Araújo,Manaus/AM,26,gomes.araújo.borges.luiz@hotmail.com,AM,Manaus
26,Flávia Nunes Martins Ribeiro Coelho,"Salvador,BA",27,nunes.flávia.coelho.martins.ribeiro@protonmail...,BA,Salvador
27,Bianca Rodrigues,"PR , Antonina",28,rodrigues.bianca@icloud.com,PR,Antonina
28,Gabriela Moraes Macedo Nunes,"CE,Fortaleza",29,moraes.nunes.gabriela.macedo@icloud.com,CE,Fortaleza
29,Victor Araújo Azevedo Tavares Correia,Itacoatiara - AM,30,araújo.tavares.azevedo.victor.correia@gmail.com,AM,Itacoatiara
30,Jéssica Figueiredo Leite Martins,"São Luís,MA",31,jéssica.martins.leite.figueiredo@tutanota.com,MA,São Luís
31,Daniela Teixeira Antunes Coelho Batista,BA - Porto Seguro,32,antunes.coelho.batista.teixeira.daniela@hotmai...,BA,Porto Seguro
32,Diego Costa Guedes Cunha,Rio Grande/RS,33,guedes.cunha.costa.diego@outlook.com,RS,Rio Grande
33,Victor Vieira Nunes Cunha,Fortaleza / CE,34,nunes.cunha.victor.vieira@protonmail.com,CE,Fortaleza
34,Priscila Martins,João Pessoa / PB,35,martins.priscila@tutanota.com,PB,João Pessoa
35,Francisca Ribeiro Pinheiro,Belém/PA,36,ribeiro.francisca.pinheiro@aol.com,PA,Belém
36,Jéssica Pimentel Borges Nunes Teixeira,"MA , Itaqui (São Luís)",37,nunes.borges.teixeira.pimentel.jéssica@yahoo.com,MA,Itaqui (São Luís)
37,Mateus Antunes,TO/Fortaleza do Tabocão,38,mateus.antunes@gmail.com,TO,Fortaleza do Tabocão
38,Renata Oliveira Siqueira,PE / Suape (Ipojuca),39,oliveira.renata.siqueira@aol.com,PE,Suape (Ipojuca)
39,Lucas Pacheco,"Corumbá,MS",40,pacheco.lucas@aol.com,MS,Corumbá
40,Pedro Ribeiro Costa Santos Correia,BA / Aratu (Candeias),41,costa.correia.ribeiro.santos.pedro@yahoo.com,BA,Aratu (Candeias)
41,Márcia Figueiredo,Vila do Conde (Barcarena) - PA,42,márcia.figueiredo@protonmail.com,PA,Vila do Conde (Barcarena)
42,Jéssica Farias Cunha,MA/Itaqui (São Luís),43,farias.jéssica.cunha@outlook.com,MA,Itaqui (São Luís)
43,Rafael Paiva Vieira,Paranaguá / PR,44,rafael.vieira.paiva@icloud.com,PR,Paranaguá
44,Amanda Santos Figueiredo Rodrigues Siqueira,"Santarém,PA",45,figueiredo.siqueira.rodrigues.amanda.santos@tu...,PA,Santarém
45,Ana Silva Costa Farias Coelho,Macapá/AP,46,costa.farias.coelho.ana.silva@hotmail.com,AP,Macapá
46,Gabriela Barros Lacerda,RJ / Niterói,47,lacerda.gabriela.barros@tutanota.com,RJ,Niterói
47,Letícia Torres Peixoto Oliveira,PE - Suape (Ipojuca),48,torres.oliveira.peixoto.letícia@yahoo.com,PE,Suape (Ipojuca)
48,Diego Costa Tavares Antunes,SE/Aracaju,49,costa.tavares.antunes.diego@icloud.com,SE,Aracaju

In [65]:
df_clientes.rename(columns={'full_name': 'nome_cliente', 'code': 'id_client', 'email': 'email_client'}, inplace=True)
df_clientes.head()

,nome_cliente,location,id_client,email_client,estado,cidade
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com,BA,Aratu (Candeias)
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com,PE,Recife
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro@gmail.com,RS,Rio Grande
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira@gmail.com,AC,Rio Branco
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas@icloud.com,PA,Santarém Novo

## Tratamento custos importação

In [ ]:
dados_historicos = df_custos_importacao["historic_data"]

df_dados_historicos_explodidos = dados_historicos.explode("historic_data")
df_final = pd.json_normalize(df_dados_historicos_explodidos)
df_custos_importacao = df_custos_importacao.drop(columns=['historic_data'])
df_custos_importacao = pd.concat([df_custos_importacao, df_final], axis = 1)
df_custos_importacao.tail()

,product_id,product_name,category,start_date,usd_price
0,1.0,Transponder AIS Maré Magnum,eletrônicos,10/08/2016,10583.63
1,2.0,Transponder Furuno Marlin,eletrônicos,15/06/2018,8778.36
2,3.0,Radar Furuno Pulse Leviathan,eletrônicos,25/09/2018,8023.87
3,4.0,Rádio AIS Hydro Tidal Zen,eletrônicos,19/03/2019,8772.78
4,5.0,Piloto Automático Furuno Storm,eletrônicos,17/01/2020,7918.18

In [14]:
df_custos_importacao.tail()

,product_id,product_name,category,historic_data
145,146,Corrente Delta Vox Ion,ancoragem,"[{'start_date': '03/05/2016', 'usd_price': 139..."
146,147,Corrente Danforth Force Leviathan Impulse,ancoragem,"[{'start_date': '13/05/2016', 'usd_price': 864..."
147,148,Âncora Delta Force Barracuda Mako,ancoragem,"[{'start_date': '06/06/2017', 'usd_price': 145..."
148,149,Cabo de Nylon Bruce Core,ancoragem,"[{'start_date': '19/02/2016', 'usd_price': 287..."
149,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"[{'start_date': '28/11/2018', 'usd_price': 426..."

In [67]:
df_custos_importacao["product_id"] = df_custos_importacao["product_id"].astype('Int64')
df_custos_importacao.head()

,product_id,product_name,category,start_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,10/08/2016,10583.63
1,2,Transponder Furuno Marlin,eletrônicos,15/06/2018,8778.36
2,3,Radar Furuno Pulse Leviathan,eletrônicos,25/09/2018,8023.87
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,19/03/2019,8772.78
4,5,Piloto Automático Furuno Storm,eletrônicos,17/01/2020,7918.18

In [68]:
df_custos_importacao["start_date"] = pd.to_datetime(df_custos_importacao["start_date"], format='%d/%m/%Y')
#df_custos_importacao["start_date"] = df_custos_importacao["start_date"].dt.strftime('%d-%m-%Y')

df_custos_importacao.head()

,product_id,product_name,category,start_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,2016-08-10,10583.63
1,2,Transponder Furuno Marlin,eletrônicos,2018-06-15,8778.36
2,3,Radar Furuno Pulse Leviathan,eletrônicos,2018-09-25,8023.87
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,2019-03-19,8772.78
4,5,Piloto Automático Furuno Storm,eletrônicos,2020-01-17,7918.18

In [69]:
df_custos_importacao.rename(columns={'product_id': 'id_produto', 'product_name': 'produto', 'category': 'categoria', }, inplace=True)
df_custos_importacao.head()

,id_produto,produto,categoria,start_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,2016-08-10,10583.63
1,2,Transponder Furuno Marlin,eletrônicos,2018-06-15,8778.36
2,3,Radar Furuno Pulse Leviathan,eletrônicos,2018-09-25,8023.87
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,2019-03-19,8772.78
4,5,Piloto Automático Furuno Storm,eletrônicos,2020-01-17,7918.18

In [70]:
df_custos_importacao.dtypes

id_produto             Int64
produto               object
categoria             object
start_date    datetime64[ns]
usd_price            float64
dtype: object